# GitHub Actions for Building, Testing, and Scanning .NET Project with Trivy and Aqua Security

name: Build & Scan

# Trigger workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Scan
  Build-and-Scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # You can modify this depending on your target framework
          
      # Step 3: Restore .NET dependencies
      - name: Restore .NET dependencies
        run: dotnet restore ./src/MySampleDotNetApp/MySampleDotNetApp.csproj

      # Step 4: Run Trivy scan (with misconfigurations, vulnerabilities, and secrets)
      - name: Run Trivy scan
        run: trivy fs --scanners misconfig,vuln,secret ./src/MySampleDotNetApp
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}

      # Step 5: Manifest Generation (Optional, for additional Aqua Security integration)
      - name: Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum -c ; then
            echo "install.sh checksum failed"
            exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url "${{ env.CSPM_URL }}" \
            --artifact-path "my-dotnet-app:${{ github.sha }}"
        env:
          CSPM_URL: ${{ env.CSPM_URL }}
          AQUA_URL: ${{ env.AQUA_URL }}
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}

